/** Asset paths for the technologies listed in the portfolio. */
export const technologyIcons: Readonly<Record<string, string>> = {
  Angular: '/icons/angular.svg',
  React: '/icons/react.svg',
  'Vue.js': '/icons/vue.svg',
  TypeScript: '/icons/typescript.svg',
  JavaScript: '/icons/javascript.svg',
  HTML: '/icons/html.svg',
  CSS: '/icons/css.svg',
  Bootstrap: '/icons/bootstrap.svg',
  'Spring Boot': '/icons/springboot.svg',
  Django: '/icons/django.svg',
  'Django REST Framework': '/icons/djangorest.svg',
  'Node.js': '/icons/nodejs.svg',
  Python: '/icons/python.svg',
  Java: '/icons/java.svg',
  C: '/icons/c.svg',
  'C++': '/icons/cpp.svg',
  Kotlin: '/icons/kotlin.svg',
  SQL: '/icons/sql.svg',
  PHP: '/icons/php.svg',
  Racket: '/icons/racket.svg',
  R: '/icons/r.svg',
  GDScript: '/icons/gdscript.svg',
  MySQL: '/icons/mysql.svg',
  PostgreSQL: '/icons/postgresql.svg',
  MongoDB: '/icons/mongodb.svg',
  Git: '/icons/git.svg',
  GitHub: '/icons/github.svg',
  Docker: '/icons/docker.svg',
  Linux: '/icons/linux.svg',
  Bash: '/icons/bash.svg',
  Godot: '/icons/godot.svg',
  Office: '/icons/office.png',
  LaTeX: '/icons/latex.svg',
  ChatGPT: '/icons/chatgpt.svg',
  Codex: '/icons/codex.svg',
  Gemini: '/icons/gemini.svg',
  Antigravity: '/icons/antigravity.png',
  'Claude Code': '/icons/claudecode.svg',
  'GitHub Copilot': '/icons/githubcopilot.svg',
  Vite: '/icons/vite.svg',
  Express: '/icons/express.svg',
  'Apache ECharts': '/icons/apacheecharts.svg',
  AngularJS: '/icons/angularjs.svg',
  'API de Bencina en Línea': '/icons/api.svg',
  Postman: '/icons/postman.svg',
  FastAPI: '/icons/fastapi.svg',
  SQLite: '/icons/sqlite.svg',
  'React Router': '/icons/reactrouter.svg',
  Vercel: '/icons/vercel.svg',
  Mongoose: '/icons/mongoose.svg',
  Playwright: '/icons/playwright.svg',
  'Django Templates': '/icons/django.svg',
};
